sonar.projectKey=HealthApp
sonar.working.directory=C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp
sonar.pullrequest.cache.basepath=C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp
sonar.sources=\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\.vs\\HealthApp.slnx\\v18\\DocumentLayout.backup.json",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\.vs\\HealthApp.slnx\\v18\\DocumentLayout.json"

14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.projectKey=HealthApp:14164E3D-8A75-A4DA-EE92-D8290D864931
14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.projectName=HealthApp
14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.projectBaseDir=C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp
14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.sourceEncoding=utf-8
14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.tests=
14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.sources=\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Constant\\TimeSlot.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Database\\AppointmentDb.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Database\\DoctorDb.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Database\\HealthRecordDb.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Database\\PatientDb.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\AppointmentAlreadyCancelledException.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\AppointmentAlreadyCompletedException.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\AppointmentConflictException.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\AppointmentNotFoundException.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\DoctorNotFoundException.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\DoctorUnavailableException.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\NoDoctorsRegisteredException.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\PastDateException.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\PatientNotFoundException.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Exceptions\\SlotAlreadyOverException.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Model\\Appointment.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Model\\Doctor.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Model\\HealthRecord.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Model\\Patient.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Program.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Repositories\\Impl\\AppointmentRepository.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Repositories\\Impl\\DoctorRepository.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Repositories\\Impl\\HealthRecordRepository.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Repositories\\Impl\\PatientRepository.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Repositories\\Interfaces\\IAppointmentRepository.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Repositories\\Interfaces\\IDoctorRepository.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Repositories\\Interfaces\\IHeathRecordRepository.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Repositories\\Interfaces\\IPatientRepository.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Services\\Impl\\AppointmentService.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Services\\Impl\\DoctorService.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Services\\Impl\\HealthRecordService.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Services\\Impl\\PatientService.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Services\\Interfaces\\IAppointmentService.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Services\\Interfaces\\IDoctorService.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Services\\Interfaces\\IHealthRecordService.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\Services\\Interfaces\\IPatientService.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\obj\\HealthApp.csproj.nuget.dgspec.json",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\obj\\project.assets.json",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\bin\\Debug\\net10.0\\HealthApp.deps.json",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\bin\\Debug\\net10.0\\HealthApp.runtimeconfig.json",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthApp\\obj\\Debug\\net10.0\\HealthApp.sourcelink.json"

14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\.sonarqube\\out\\0"
14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\.sonarqube\\out\\0\\Issues.json"
14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.cs.scanner.telemetry=\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\.sonarqube\\out\\0\\Telemetry.json"

14164E3D-8A75-A4DA-EE92-D8290D864931.sonar.working.directory=C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\.sonarqube\\out\\.sonar\\mod0
69AA97CE-0259-4604-A708-C2B6B68F4DE3.sonar.projectKey=HealthApp:69AA97CE-0259-4604-A708-C2B6B68F4DE3
69AA97CE-0259-4604-A708-C2B6B68F4DE3.sonar.projectName=HealthAppTesting
69AA97CE-0259-4604-A708-C2B6B68F4DE3.sonar.projectBaseDir=C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthAppTesting
69AA97CE-0259-4604-A708-C2B6B68F4DE3.sonar.sourceEncoding=utf-8
69AA97CE-0259-4604-A708-C2B6B68F4DE3.sonar.sources=
69AA97CE-0259-4604-A708-C2B6B68F4DE3.sonar.tests=\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthAppTesting\\obj\\HealthAppTesting.csproj.nuget.dgspec.json",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthAppTesting\\obj\\project.assets.json",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthAppTesting\\bin\\Debug\\net10.0\\HealthApp.deps.json",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthAppTesting\\bin\\Debug\\net10.0\\HealthApp.runtimeconfig.json",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthAppTesting\\bin\\Debug\\net10.0\\HealthAppTesting.deps.json",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthAppTesting\\bin\\Debug\\net10.0\\HealthAppTesting.runtimeconfig.json",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthAppTesting\\obj\\Debug\\net10.0\\HealthAppTesting.sourcelink.json",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthAppTesting\\RepositoryTesting\\AppointmentRepositoryTesting.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthAppTesting\\RepositoryTesting\\DoctorRepositoryTesting.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthAppTesting\\RepositoryTesting\\HealthRecordRepositoryTesting.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthAppTesting\\RepositoryTesting\\PatientRepositoryTesting.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthAppTesting\\ServiceTesting\\AppointmentServiceTesting.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthAppTesting\\ServiceTesting\\DoctorServiceTesting.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthAppTesting\\ServiceTesting\\HealthRecordServiceTesting.cs",\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\HealthAppTesting\\ServiceTesting\\PatientServiceTesting.cs"

69AA97CE-0259-4604-A708-C2B6B68F4DE3.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\.sonarqube\\out\\1"
69AA97CE-0259-4604-A708-C2B6B68F4DE3.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\.sonarqube\\out\\1\\Issues.json"
69AA97CE-0259-4604-A708-C2B6B68F4DE3.sonar.cs.scanner.telemetry=\
"C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\.sonarqube\\out\\1\\Telemetry.json"

69AA97CE-0259-4604-A708-C2B6B68F4DE3.sonar.working.directory=C:\\Users\\310476\\Main_HAP_Pod1\\HealthApp\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=14164E3D-8A75-A4DA-EE92-D8290D864931,69AA97CE-0259-4604-A708-C2B6B68F4DE3

